(function(){
  'use strict';
  function uuid(){return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c==='x'?r:(r&0x3|0x8);return v.toString(16);});}
  function qs(s,r){return (r||document).querySelector(s);} function qsa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));}
  function cur(n,c){try{return new Intl.NumberFormat('fr-FR',{style:'currency',currency:c||'EUR'}).format(+n||0);}catch(e){return '€'+(+n||0);}}
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m];});}
  function hash(s){var h=0,i,chr;if(!s)return'0';for(i=0;i<s.length;i++){chr=s.charCodeAt(i);h=((h<<5)-h)+chr;h|=0;}return String(h);}
  var state={settings:{currency:'EUR',theme:'auto',categories:['Logement','Courses','Transport','Santé','Divertissement','Épargne','Voyage','Abonnements','Impôts','Frais bancaires','ESE','Air Liquide','CNDX','BTC','LINK','RNDR','NEAR'],pinHash:null,pinHint:'',apiKey:''},transactions:[],budgets:[],holds:[],dca:[],goals:[]};
  function save(){try{localStorage.setItem('invest_v5_premium',JSON.stringify(state));}catch(e){}}
  function load(){try{var j=localStorage.getItem('invest_v5_premium');if(j){var o=JSON.parse(j);if(o&&typeof o==='object')state=o;}}catch(e){}}
  function applyTheme(){var t=(state.settings&&state.settings.theme)||'auto';var b=document.body;b.classList.remove('theme-auto','theme-dark','theme-light');b.classList.add('theme-'+t);var s=qs('#theme');if(s)s.value=t;}
  function lockCheck(){var p=qs('#lock');if(!p)return; if(state.settings.pinHash){p.classList.remove('hidden');var hint=qs('#pin-hint');if(hint)hint.textContent=state.settings.pinHint?('Indice: '+state.settings.pinHint):'';qs('#pin-unlock').onclick=function(){var v=(qs('#pin-input').value||'').trim();if(hash(v)===state.settings.pinHash){p.classList.add('hidden');qs('#pin-input').value='';}else{alert('PIN incorrect');}};qs('#pin-forget').onclick=function(){if(confirm('Désactiver le PIN ?')){state.settings.pinHash=null;save();p.classList.add('hidden');}};}else{p.classList.add('hidden');}}
  var routes={};
  function route(path,render){routes[path]=render;}
  function nav(){var path=location.hash.replace('#','')||'#/dashboard';qsa('.navlink').forEach(function(a){if(a.getAttribute('href')===path)a.classList.add('active');else a.classList.remove('active');});(routes[path]||routes['#/dashboard'])();}
  window.addEventListener('hashchange',nav);

  /* DASHBOARD */
  function viewDashboard(){qs('#view').innerHTML='<section class="section"><div class="grid">    <div class="card glass"><h3>Vue rapide</h3>      <div class="metrics">        <div class="metric"><div class="label">Capital total</div><div class="val" id="k_total">—</div></div>        <div class="metric"><div class="label">Variation du mois</div><div class="val" id="k_var">—</div></div>        <div class="metric"><div class="label">Taux d’épargne</div><div class="val" id="k_save">—</div></div>      </div>      <div class="muted small" id="k_note"></div>    </div>    <div class="card glass"><h3>Top catégories (mois)</h3><canvas id="bar" width="700" height="260"></canvas></div>    <div class="card glass"><h3>Flux 12 mois</h3><canvas id="line" width="900" height="260"></canvas></div>  </div></section>'; dashRender();}
  function dashRender(){var now=new Date(),y=now.getFullYear(),m=now.getMonth();var month=state.transactions.filter(function(t){var d=new Date(t.date);return d.getFullYear()===y&&d.getMonth()===m;});var inc=0,exp=0,inv=0,i;for(i=0;i<month.length;i++){var t=month[i]; if(t.type==='income')inc+=+t.amount; else if(t.type==='expense')exp+=Math.abs(+t.amount); else if(t.type==='invest')inv+=Math.abs(+t.amount);} var global=0; for(i=0;i<state.transactions.length;i++){var tt=state.transactions[i]; if(tt.type==='income')global+=+tt.amount; else if(tt.type==='expense'||tt.type==='invest')global-=Math.abs(+tt.amount);} var k_total=qs('#k_total'); if(k_total) k_total.textContent=cur(global,state.settings.currency); var k_var=qs('#k_var'); if(k_var) k_var.textContent=cur(inc-exp-inv,state.settings.currency); var k_save=qs('#k_save'); if(k_save) k_save.textContent=(inc?(((inc-exp-inv)/Math.max(1,inc))*100).toFixed(1)+'%':'—'); var note=qs('#k_note'); if(note) note.textContent='Astuce: suivez vos DCA et vos budgets pour améliorer le taux d’épargne.';
    var byCat={},t; for(i=0;i<month.length;i++){t=month[i]; if(t.type==='expense') byCat[t.category]=(byCat[t.category]||0)+Math.abs(+t.amount);} var ent=[],k; for(k in byCat) if(byCat.hasOwnProperty(k)) ent.push([k,byCat[k]]); ent.sort(function(a,b){return b[1]-a[1];}); ent=ent.slice(0,8); chartBars('bar',ent,state.settings.currency);
    var months=[],a=[],b=[],c=[]; for(i=11;i>=0;i--){var d=new Date(y,m-i,1); var yy=d.getFullYear(),mm=d.getMonth(); var tx=state.transactions.filter(function(tt){var dt=new Date(tt.date);return dt.getFullYear()===yy&&dt.getMonth()===mm;}); var A=0,B=0,C=0; for(var j=0;j<tx.length;j++){var x=tx[j]; if(x.type==='income')A+=+x.amount; else if(x.type==='expense')B+=Math.abs(+x.amount); else if(x.type==='invest')C+=Math.abs(+x.amount);} months.push(d.toLocaleString('fr-FR',{month:'short'})); a.push(A); b.push(B); c.push(A-B-C);} chartLine('line',months,a,b,c); }

  /* TRANSACTIONS */
  function viewTx(){qs('#view').innerHTML='<section class="section"><h3>Transactions</h3>    <form id="txf" class="form">      <label>Type<select id="tt"><option value="income">Revenu</option><option value="expense">Dépense</option><option value="invest">Investissement</option><option value="transfer">Virement</option></select></label>      <label>Date<input type="date" id="td"/></label>      <label>Compte<select id="ta"><option>Banque</option><option>PEA</option><option>CTO</option><option>Crypto</option></select></label>      <label>Catégorie<input list="cats" id="tc"/><datalist id="cats"></datalist></label>      <label>Description<input id="te" placeholder="Note"/></label>      <label>Montant (€)<input id="tm" type="number" step="0.01"/></label>      <button class="btn btn-primary">Ajouter</button>    </form>    <div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Type</th><th>Compte</th><th>Catégorie</th><th>Description</th><th>Montant</th><th></th></tr></thead><tbody id="tb"></tbody></table></div>    <div class="row" style="margin-top:8px;"><input class="input" id="tq" placeholder="Rechercher…"/><button id="tclr" class="btn btn-danger">Tout supprimer</button></div></section>'; bindTx();}
  function bindTx(){var dl=qs('#cats'); dl.innerHTML=''; for(var i=0;i<state.settings.categories.length;i++){var o=document.createElement('option'); o.value=state.settings.categories[i]; dl.appendChild(o);} try{qs('#td').valueAsDate=new Date();}catch(e){} qs('#txf').addEventListener('submit',function(e){e.preventDefault(); var amt=+qs('#tm').value||0; if(!qs('#td').value||!amt){alert('Date et montant requis');return;} var tx={id:uuid(),type:qs('#tt').value,date:qs('#td').value,account:qs('#ta').value,category:qs('#tc').value||'(Non classé)',desc:qs('#te').value||'',amount:amt}; state.transactions.unshift(tx); save(); renderTx(); dashRender();}); qs('#tq').addEventListener('input',renderTx); qs('#tclr').addEventListener('click',function(){ if(confirm('Supprimer toutes les transactions ?')){state.transactions=[]; save(); renderTx(); dashRender();}}); renderTx();}
  function renderTx(){var tb=qs('#tb'); tb.innerHTML=''; var q=(qs('#tq').value||'').toLowerCase(); for(var i=0;i<state.transactions.length;i++){var t=state.transactions[i]; if(JSON.stringify(t).toLowerCase().indexOf(q)===-1) continue; var tr=document.createElement('tr'); tr.innerHTML='<td>'+t.date+'</td><td>'+t.type+'</td><td>'+t.account+'</td><td>'+t.category+'</td><td>'+esc(t.desc)+'</td><td>'+cur(t.amount,state.settings.currency)+'</td><td><button class="del" data-id="'+t.id+'">✕</button></td>'; tb.appendChild(tr);} qsa('button.del',tb).forEach(function(b){b.addEventListener('click',function(){var id=b.getAttribute('data-id'); state.transactions=state.transactions.filter(function(x){return x.id!==id;}); save(); renderTx(); dashRender();});});}

  /* BUDGETS */
  function viewBdg(){qs('#view').innerHTML='<section class="section"><h3>Budgets mensuels</h3>    <form id="bf" class="form"><label>Catégorie<input id="bc"/></label><label>Montant (€)<input id="ba" type="number" step="0.01"/></label><button class="btn btn-primary">Ajouter / MAJ</button></form>    <div class="table-wrap"><table class="table"><thead><tr><th>Catégorie</th><th>Budget</th><th>Dépensé</th><th>Reste</th><th></th></tr></thead><tbody id="bb"></tbody></table></div></section>'; bindBdg();}
  function bindBdg(){qs('#bf').addEventListener('submit',function(e){e.preventDefault(); var c=(qs('#bc').value||'').trim(); var a=+qs('#ba').value||0; if(!c){alert('Catégorie requise');return;} var i,idx=-1; for(i=0;i<state.budgets.length;i++){ if((state.budgets[i].category||'').toLowerCase()===c.toLowerCase()){idx=i;break;} } if(idx>=0) state.budgets[idx].amount=a; else state.budgets.push({category:c,amount:a}); save(); this.reset(); renderBdg();}); renderBdg();}
  function renderBdg(){var tb=qs('#bb'); tb.innerHTML=''; var now=new Date(),y=now.getFullYear(),m=now.getMonth(); var ex=state.transactions.filter(function(t){var d=new Date(t.date);return d.getFullYear()===y&&d.getMonth()===m&&t.type==='expense';}); for(var i=0;i<state.budgets.length;i++){var b=state.budgets[i],spent=0; for(var j=0;j<ex.length;j++){var t=ex[j]; if((t.category||'').toLowerCase()===(b.category||'').toLowerCase()) spent+=Math.abs(+t.amount);} var left=(+b.amount||0)-spent; var tr=document.createElement('tr'); tr.innerHTML='<td>'+b.category+'</td><td>'+cur(b.amount,state.settings.currency)+'</td><td>'+cur(spent,state.settings.currency)+'</td><td>'+cur(left,state.settings.currency)+'</td><td><button class="del" data-cat="'+b.category+'">✕</button></td>'; tb.appendChild(tr);} qsa('button.del',tb).forEach(function(b){b.addEventListener('click',function(){var c=b.getAttribute('data-cat'); state.budgets=state.budgets.filter(function(x){return x.category!==c;}); save(); renderBdg();});});}

  /* INVEST */
  function viewInv(){qs('#view').innerHTML='<section class="section"><h3>Investissements (PEA / CTO / Crypto)</h3>    <div class="split"><div class="card glass"><h3>Lignes & cibles</h3>    <form id="hf" class="form"><label>Compte<select id="ha"><option>PEA</option><option>CTO</option><option>Crypto</option></select></label>    <label>Actif<input id="hs"/></label><label>Cible (%)<input id="ht" type="number" step="0.1"/></label>    <label>Valeur (€)<input id="hv" type="number" step="0.01"/></label><button class="btn btn-primary">Ajouter / MAJ</button></form>    <div class="table-wrap"><table class="table"><thead><tr><th>Compte</th><th>Actif</th><th>Valeur</th><th>Cible</th><th>Écart</th><th></th></tr></thead><tbody id="hb"></tbody></table></div>    <button id="preset" class="btn" style="margin-top:8px;">➕ Appliquer mes presets</button></div>    <div class="card glass"><h3>Plan DCA mensuel</h3>    <form id="df" class="form"><label>Actif<input id="ds"/></label><label>Montant/mois (€)<input id="da" type="number"/></label><label>Jour (1–28)<input id="dd" type="number" min="1" max="28" value="5"/></label><button class="btn btn-primary">Ajouter / MAJ</button></form>    <div class="table-wrap"><table class="table"><thead><tr><th>Actif</th><th>Montant</th><th>Jour</th><th>Prochain</th><th></th></tr></thead><tbody id="db"></tbody></table></div></div></div></section>'; bindInv();}
  function bindInv(){qs('#hf').addEventListener('submit',function(e){e.preventDefault(); var a=qs('#ha').value,s=(qs('#hs').value||'').trim(),t=+qs('#ht').value||0,v=+qs('#hv').value||0; if(!s){alert('Actif requis');return;} var i,idx=-1; for(i=0;i<state.holds.length;i++){var h=state.holds[i]; if((h.account+'|'+h.asset).toLowerCase()===(a+'|'+s).toLowerCase()){idx=i;break;}} if(idx>=0){state.holds[idx].target=t; state.holds[idx].value=v;} else {state.holds.push({account:a,asset:s,target:t,value:v});} save(); this.reset(); renderHold();}); qs('#df').addEventListener('submit',function(e){e.preventDefault(); var s=(qs('#ds').value||'').trim(),amt=+qs('#da').value||0,day=+qs('#dd').value||1; if(!s){alert('Actif requis');return;} var i,idx=-1; for(i=0;i<state.dca.length;i++){ if((state.dca[i].asset||'').toLowerCase()===s.toLowerCase()){idx=i;break;} } if(idx>=0){state.dca[idx].amount=amt; state.dca[idx].day=day;} else {state.dca.push({asset:s,amount:amt,day:day});} save(); this.reset(); renderDCA();}); qs('#preset').addEventListener('click',applyPresets); renderHold(); renderDCA();}
  function renderHold(){var tb=qs('#hb'); tb.innerHTML=''; var tot=0,i; for(i=0;i<state.holds.length;i++){tot+=+state.holds[i].value||0;} for(i=0;i<state.holds.length;i++){var h=state.holds[i],want=tot*((+h.target||0)/100),diff=want-(+h.value||0); var tr=document.createElement('tr'); tr.innerHTML='<td>'+h.account+'</td><td>'+h.asset+'</td><td>'+cur(h.value,state.settings.currency)+'</td><td>'+(+h.target||0).toFixed(1)+'%</td><td>'+cur(diff,state.settings.currency)+'</td><td><button class="del" data-k="'+h.account+'|'+h.asset+'">✕</button></td>'; tb.appendChild(tr);} qsa('button.del',tb).forEach(function(b){b.addEventListener('click',function(){var p=b.getAttribute('data-k').split('|'); state.holds=state.holds.filter(function(x){return !(x.account===p[0]&&x.asset===p[1]);}); save(); renderHold();});});}
  function renderDCA(){var tb=qs('#db'); tb.innerHTML=''; var now=new Date(),today=now.getDate(); for(var i=0;i<state.dca.length;i++){var d=state.dca[i],next; if(today>+d.day){next=new Date(now.getFullYear(),now.getMonth()+1,+d.day);} else {next=new Date(now.getFullYear(),now.getMonth(),+d.day);} var tr=document.createElement('tr'); tr.innerHTML='<td>'+d.asset+'</td><td>'+cur(d.amount,state.settings.currency)+'</td><td>'+d.day+'</td><td>'+next.toISOString().slice(0,10)+'</td><td><button class="del" data-a="'+d.asset+'">✕</button></td>'; tb.appendChild(tr);} qsa('button.del',tb).forEach(function(b){b.addEventListener('click',function(){var a=b.getAttribute('data-a'); state.dca=state.dca.filter(function(x){return x.asset!==a;}); save(); renderDCA();});});}
  function applyPresets(){var H=[{account:'PEA',asset:'ESE (BNP Easy S&P 500 EURH C)',target:50,value:3520.73},{account:'PEA',asset:'Air Liquide',target:20,value:695.12},{account:'PEA',asset:'Amundi MSCI Emerging Markets (PEA)',target:10,value:517.00},{account:'CTO',asset:'CNDX (iShares Nasdaq 100 Acc)',target:10,value:0},{account:'Crypto',asset:'BTC',target:4.5,value:296.95},{account:'Crypto',asset:'LINK',target:2.6,value:169.67},{account:'Crypto',asset:'RNDR',target:1.5,value:47.19},{account:'Crypto',asset:'NEAR',target:1.7,value:101.85}], D=[{asset:'ESE (BNP Easy S&P 500 EURH C)',amount:300,day:5},{asset:'Air Liquide',amount:100,day:6},{asset:'CNDX (iShares Nasdaq 100 Acc)',amount:250,day:10},{asset:'BTC',amount:45,day:3},{asset:'LINK',amount:45,day:3},{asset:'RNDR',amount:37.5,day:3},{asset:'NEAR',amount:22.5,day:3}]; var i,j; for(i=0;i<H.length;i++){var ph=H[i],idx=-1; for(j=0;j<state.holds.length;j++){var h=state.holds[j]; if((h.account+'|'+h.asset).toLowerCase()===(ph.account+'|'+ph.asset).toLowerCase()){idx=j;break;}} if(idx>=0){state.holds[idx].target=ph.target; if(ph.value) state.holds[idx].value=ph.value;} else {state.holds.push(ph);} } for(i=0;i<D.length;i++){var pd=D[i],id=-1; for(j=0;j<state.dca.length;j++){ if((state.dca[j].asset||'').toLowerCase()===(pd.asset||'').toLowerCase()){id=j;break;} } if(id>=0){state.dca[id].amount=pd.amount; state.dca[id].day=pd.day;} else {state.dca.push(pd);} } save(); alert('Presets appliqués'); nav();}

  /* GOALS */
  function viewGoals(){qs('#view').innerHTML='<section class="section"><h3>Objectifs financiers</h3>    <form id="gf" class="form">      <label>Nom<input id="gn" placeholder="Ex: Atteindre 50 000 €"/></label>      <label>Type<select id="gt"><option value="networth">Capital total</option><option value="saving">Épargne mensuelle</option></select></label>      <label>Cible (€)<input id="ga" type="number" step="0.01"/></label>      <label>Échéance<input id="gd" type="date"/></label>      <button class="btn btn-primary">Ajouter / MAJ</button>    </form>    <div class="table-wrap"><table class="table"><thead><tr><th>Nom</th><th>Type</th><th>Cible</th><th>Progression</th><th>Échéance</th><th></th></tr></thead><tbody id="gb"></tbody></table></div></section>'; bindGoals();}
  function bindGoals(){qs('#gf').addEventListener('submit',function(e){e.preventDefault(); var n=(qs('#gn').value||'').trim(),t=qs('#gt').value,a=+qs('#ga').value||0,d=qs('#gd').value||''; if(!n||!a){alert('Nom et cible requis');return;} var idx=-1; for(var i=0;i<state.goals.length;i++){ if(state.goals[i].name.toLowerCase()===n.toLowerCase()){idx=i;break;} } var g={name:n,type:t,target:a,due:d}; if(idx>=0) state.goals[idx]=g; else state.goals.push(g); save(); renderGoals();}); renderGoals();}
  function renderGoals(){var tb=qs('#gb'); tb.innerHTML=''; var progressData=goalProgress(); for(var i=0;i<state.goals.length;i++){var g=state.goals[i]; var pr=progressData[g.name]||{ratio:0,label:'—'}; var tr=document.createElement('tr'); tr.innerHTML='<td>'+esc(g.name)+'</td><td>'+g.type+'</td><td>'+cur(g.target,state.settings.currency)+'</td><td style="min-width:220px;"><div class="bar"><span style="width:'+(Math.min(100,Math.max(0,pr.ratio*100))).toFixed(0)+'%"></span></div><div class="small">'+esc(pr.label)+'</div></td><td>'+(g.due||'')+'</td><td><button class="del" data-n="'+esc(g.name)+'">✕</button></td>'; tb.appendChild(tr);} qsa('button.del',tb).forEach(function(b){b.addEventListener('click',function(){var n=b.getAttribute('data-n'); state.goals=state.goals.filter(function(x){return x.name!==n;}); save(); renderGoals();});});}
  function goalProgress(){var res={}, now=new Date(), y=now.getFullYear(), m=now.getMonth(); var month=state.transactions.filter(function(t){var d=new Date(t.date);return d.getFullYear()===y&&d.getMonth()===m;}); var inc=0,exp=0,inv=0; for(var i=0;i<month.length;i++){var t=month[i]; if(t.type==='income')inc+=+t.amount; else if(t.type==='expense')exp+=Math.abs(+t.amount); else if(t.type==='invest')inv+=Math.abs(+t.amount);} var global=0; for(i=0;i<state.transactions.length;i++){var tt=state.transactions[i]; if(tt.type==='income')global+=+tt.amount; else if(tt.type==='expense'||tt.type==='invest')global-=Math.abs(+tt.amount);} for(i=0;i<state.goals.length;i++){var g=state.goals[i]; if(g.type==='networth'){var ratio=global/Math.max(1,g.target);res[g.name]={ratio:ratio,label:cur(global)+' / '+cur(g.target)};} else if(g.type==='saving'){var saving=inc-exp-inv; var ratio=saving/Math.max(1,g.target);res[g.name]={ratio:ratio,label:cur(saving)+' / '+cur(g.target)+' ce mois'};} } return res;}

  /* ANALYSIS */
  function viewAnalysis(){qs('#view').innerHTML='<section class="section"><h3>Analyses & Conseils</h3>    <div class="grid">      <div class="card glass"><h3>Ratios clés</h3><div id="ratios"></div></div>      <div class="card glass"><h3>Alertes & recommandations</h3><ul id="reco"></ul></div>      <div class="card glass"><h3>API (optionnel)</h3>        <p class="muted small">Entrez une clé API si vous souhaitez des conseils enrichis (sinon, les analyses locales suffisent).</p>        <div class="row"><input id="apiKey" class="input" placeholder="Clé API (optionnel)"/><button id="saveApi" class="btn">Enregistrer</button></div>      </div>    </div></section>'; runAnalysis(); qs('#saveApi').onclick=function(){ state.settings.apiKey=(qs('#apiKey').value||'').trim(); save(); alert('Clé enregistrée'); }; var k=qs('#apiKey'); if(k) k.value=state.settings.apiKey||''; }
  function runAnalysis(){var ratios=qs('#ratios'), reco=qs('#reco'); ratios.innerHTML=''; reco.innerHTML=''; var now=new Date(), y=now.getFullYear(), m=now.getMonth(); var month=state.transactions.filter(function(t){var d=new Date(t.date);return d.getFullYear()===y&&d.getMonth()===m;}); var inc=0,exp=0,inv=0; for(var i=0;i<month.length;i++){var t=month[i]; if(t.type==='income')inc+=+t.amount; else if(t.type==='expense')exp+=Math.abs(+t.amount); else if(t.type==='invest')inv+=Math.abs(+t.amount);} var saving=inc-exp-inv; var rate=inc?((saving/inc)*100):0; var tot=0; for(i=0;i<state.holds.length;i++){tot+=+state.holds[i].value||0;} var crypto=0; for(i=0;i<state.holds.length;i++){if(state.holds[i].account==='Crypto') crypto+=+state.holds[i].value||0;} var cryptoShare=tot?((crypto/tot)*100):0;
    function addRatio(label,value){var p=document.createElement('div'); p.className='row'; p.innerHTML='<div style="min-width:160px" class="muted">'+label+'</div><strong>'+value+'</strong>'; ratios.appendChild(p);}
    addRatio('Épargne du mois', cur(saving,state.settings.currency)+' ('+rate.toFixed(1)+'%)');
    addRatio('Capital investi', cur(tot,state.settings.currency));
    addRatio('Part Crypto', cryptoShare.toFixed(1)+'%');
    function addReco(txt){var li=document.createElement('li'); li.textContent=txt; reco.appendChild(li);}
    if(rate<10) addReco('Taux d’épargne faible : envisage de réduire 1–2 catégories de dépense ce mois.'); else addReco('Bon taux d’épargne, continue sur cette lancée !');
    if(cryptoShare>20) addReco('La part crypto dépasse 20% du portefeuille : évalue le risque et pense au rééquilibrage.');
    if(state.dca.length===0) addReco('Tu n’as pas de DCA configuré : ajoute 1–2 lignes pour lisser tes entrées.');
    if(state.settings.apiKey){ addReco('Analyses API activées (clé enregistrée).'); }
  }

  /* IO */
  function viewIO(){qs('#view').innerHTML='<section class="section"><h3>Import / Export</h3>    <div class="row"><button id="exj" class="btn btn-primary">Exporter JSON</button><button id="exc" class="btn">Exporter CSV (transactions)</button>    <label class="btn">Import JSON<input id="imj" type="file" accept=".json" style="display:none"/></label></div>    <div class="row" style="margin-top:8px;"><select id="csvsrc" class="select"><option value="generic">CSV générique</option><option value="boursorama">Boursorama</option><option value="traderepublic">Trade Republic</option></select>    <label class="btn">Importer CSV<input id="imc" type="file" accept=".csv" style="display:none"/></label></div>    <p class="muted small">Les données restent locales. Pensez à sauvegarder le JSON.</p></section>'; bindIO();}
  function bindIO(){qs('#exj').onclick=function(){var data=JSON.stringify(state,null,2); dl('invest_v5_premium.json',data,'application/json');}; qs('#exc').onclick=function(){var header='date,type,account,category,desc,amount\n'; var rows=state.transactions.map(function(t){return [t.date,t.type,t.account,esc(t.category),esc(t.desc),t.amount].join(',');}); dl('transactions.csv',header+rows.join('\n'),'text/csv');}; qs('#imj').addEventListener('change',function(e){var f=e.target.files[0]; if(!f) return; var fr=new FileReader(); fr.onload=function(){try{var d=JSON.parse(fr.result); if(!d.transactions) throw new Error('Fichier invalide'); state=d; save(); applyTheme(); nav(); lockCheck(); alert('Import réussi');}catch(err){alert('Import raté: '+err.message);} }; fr.readAsText(f);}); qs('#imc').addEventListener('change',function(e){var f=e.target.files[0]; if(!f) return; var src=qs('#csvsrc').value; var fr=new FileReader(); fr.onload=function(){ try{var rows=parseCSV(fr.result); if(src==='generic') importGeneric(rows); else if(src==='boursorama') importBoursorama(rows); else importTR(rows); save(); alert('Import CSV réussi'); nav(); }catch(err){ alert('Import CSV raté: '+err.message); } }; fr.readAsText(f);});}
  function parseCSV(txt){var lines=txt.replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n'); var rows=[]; for(var i=0;i<lines.length;i++){var line=lines[i]; if(!line.trim()) continue; var cells=[],cur='',inQ=false; for(var j=0;j<line.length;j++){var ch=line[j]; if(ch==='"'){ if(inQ && line[j+1]==='"'){ cur+='"'; j++; } else { inQ=!inQ; } } else if(ch===',' && !inQ){ cells.push(cur); cur=''; } else { cur+=ch; } } cells.push(cur); rows.push(cells);} return rows;}
  function importGeneric(rows){var h=rows[0].map(function(s){return String(s).trim().toLowerCase();}); function id(k){return h.indexOf(k);} if(id('date')<0||id('type')<0||id('amount')<0) throw new Error('En-têtes requis: date,type,amount'); for(var i=1;i<rows.length;i++){var r=rows[i]; if(!r||!r.length) continue; var tx={id:uuid(),date:r[id('date')],type:r[id('type')],account:r[id('account')]||'Banque',category:r[id('category')]||'(Non classé)',desc:r[id('desc')]||'',amount:+String(r[id('amount')]||'0').replace(',','.')}; if(!tx.date) continue; state.transactions.unshift(tx);}}
  function importBoursorama(rows){var h=rows[0].map(function(s){return String(s).trim().toLowerCase();}); var iDate=h.indexOf('date'); var iLib=h.indexOf('libellé'); if(iLib<0) iLib=h.indexOf('libelle'); var iCat=h.indexOf('catégorie'); if(iCat<0) iCat=h.indexOf('categorie'); var iAmt=h.indexOf('montant'); if(iDate<0||iAmt<0) throw new Error('Format Boursorama non reconnu'); for(var i=1;i<rows.length;i++){var r=rows[i]; if(!r||!r.length) continue; var amt=String(r[iAmt]||'0').replace('€','').replace(' ','').replace(',','.'); var v=parseFloat(amt)||0; var t={id:uuid(),date:r[iDate],type:(v<0?'expense':'income'),account:'Banque',category:iCat>=0?(r[iCat]||'Boursorama'):'Boursorama',desc:iLib>=0?(r[iLib]||''):'' ,amount:Math.abs(v)}; if(!t.date) continue; state.transactions.unshift(t);}}
  function importTR(rows){var h=rows[0].map(function(s){return String(s).trim().toLowerCase();}); var iDate=h.indexOf('date'), iAmt=h.indexOf('amount'); if(iDate<0||iAmt<0){ iDate=0; iAmt=rows[0].length-1; } for(var i=1;i<rows.length;i++){var r=rows[i]; if(!r||!r.length) continue; var amt=+String(r[iAmt]||'0').replace(',','.'); var txType=amt<0?'expense':'income'; var tx={id:uuid(),date:r[iDate],type:txType,account:'CTO',category:(h.indexOf('type')>=0?(r[h.indexOf('type')]||'TR'):'TR'),desc:(h.indexOf('note')>=0?(r[h.indexOf('note')]||''):'') ,amount:Math.abs(amt)}; if(!tx.date) continue; state.transactions.unshift(tx);}}

  /* SETTINGS */
  function viewSet(){qs('#view').innerHTML='<section class="section"><h3>Paramètres</h3>    <div class="form"><label>Thème<select id="th"><option value="auto">Auto</option><option value="dark">Sombre</option><option value="light">Clair</option></select></label>    <label>Devise<select id="cu"><option value="EUR">EUR (€)</option><option value="USD">USD ($)</option></select></label>    <label>Catégories suggérées<input id="cg" placeholder="Courses, Logement, ..."/></label>    <label>Code PIN<input id="pin" type="password" maxlength="6" placeholder="(vide pour désactiver)"/></label>    <label>Indice PIN<input id="pinh" placeholder="indice (optionnel)"/></label>    <button id="sav" class="btn btn-primary">Enregistrer</button><button id="rst" class="btn btn-danger">Réinitialiser TOUT</button></div></section>'; bindSet();}
  function bindSet(){var th=qs('#th'),cu=qs('#cu'),cg=qs('#cg'),pin=qs('#pin'),pinh=qs('#pinh'); th.value=state.settings.theme; cu.value=state.settings.currency; cg.value=state.settings.categories.join(', '); qs('#sav').onclick=function(){state.settings.theme=th.value; state.settings.currency=cu.value; var list=cg.value.split(','); var out=[]; for(var i=0;i<list.length;i++){var s=(list[i]||'').trim(); if(s) out.push(s);} if(out.length) state.settings.categories=out; var p=(pin.value||'').trim(); state.settings.pinHash=p?hash(p):null; state.settings.pinHint=pinh.value||''; save(); applyTheme(); lockCheck(); alert('Paramètres enregistrés');}; qs('#rst').onclick=function(){ if(confirm('Supprimer TOUTES les données ?')){ localStorage.removeItem('invest_v5_premium'); location.reload(); }};}

  /* CHARTS */
  function chartBars(id, entries, currency){var c=qs('#'+id); if(!c) return; var x=c.getContext('2d'); x.clearRect(0,0,c.width,c.height); var max=1; for(var i=0;i<entries.length;i++) if(entries[i][1]>max) max=entries[i][1]; var pad=20, barH=24, gap=10, left=160; x.fillStyle='#9aa3bb'; x.font='12px system-ui'; for(i=0;i<entries.length;i++){var e=entries[i], y=pad+10+i*(barH+gap); x.fillStyle='#9aa3bb'; x.fillText(e[0],10,y+16); var w=(c.width-left-pad)*(e[1]/max); x.fillStyle='#6ea8fe'; x.fillRect(left,y,w,barH); x.fillStyle='#eef2ff'; x.fillText(cur(e[1],currency), left+w+6, y+16);} if(entries.length===0){x.fillStyle='#9aa3bb'; x.fillText('Aucune donnée.',10,60);}}
  function chartLine(id, months, a1,a2,a3){var c=qs('#'+id); if(!c) return; var x=c.getContext('2d'); x.clearRect(0,0,c.width,c.height); var W=c.width,H=c.height,p=36; function mm(a,fn){var v=a[0]||0; for(var i=1;i<a.length;i++) v=fn(v,a[i]); return v;} var all=a1.concat(a2).concat(a3); var max=mm(all,Math.max),min=mm(all,Math.min); if(max===min){max=min+1;} function Y(v){return p+(H-2*p)*(1-(v-min)/(max-min));} function X(i){return p+i*((W-2*p)/((months.length-1)||1));} x.strokeStyle='#2a3770'; x.lineWidth=1; x.beginPath(); for(var i=0;i<5;i++){var yy=p+i*((H-2*p)/4); x.moveTo(p,yy); x.lineTo(W-p,yy);} x.stroke(); function draw(a,col){x.strokeStyle=col; x.beginPath(); for(var i=0;i<a.length;i++){var xx=X(i),yy=Y(a[i]); if(i===0)x.moveTo(xx,yy); else x.lineTo(xx,yy);} x.stroke();} draw(a1,'#95f7c2'); draw(a2,'#ef6b6b'); draw(a3,'#6ea8fe'); x.fillStyle='#9aa3bb'; x.font='11px system-ui'; for(i=0;i<months.length;i++){var xx=X(i); x.fillText(months[i], xx-12, H-p+14);}}

  /* IO Helpers */
  function dl(name,content,type){var a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([content],{type:type})); a.download=name; a.click();}

  /* ROUTES */
  function init(){load(); applyTheme(); route('#/dashboard',viewDashboard); route('#/transactions',viewTx); route('#/budgets',viewBdg); route('#/invest',viewInv); route('#/goals',viewGoals); route('#/analysis',viewAnalysis); route('#/io',viewIO); route('#/settings',viewSet); nav(); var tsel=qs('#theme'); if(tsel) tsel.onchange=function(){state.settings.theme=tsel.value; save(); applyTheme();}; setTimeout(function(){var sp=qs('#splash'); if(sp) sp.classList.add('hidden');},450); lockCheck();}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);} else {init();}
})();